### ISSUE TITLE
Determine & Document RC Car Hardware Specs

### ISSUE THREAD

**Issue by Cakem1x** [Cakem1x/brumm#2]
Find out the hardware specs of the RC Car and document them in the wiki:
https://github.com/Cakem1x/brumm/wiki/Hardware#rc-car-stock-hardware

Important things I can think of atm:
* Power Supply
* Steering
  * voltage?
  * Servo's PWM min/max values?
* Main motor (brrrrrummmmmm )
  * How can we control it?

Start by measuring what the RC receiver is putting on the line...

**Comment by Motonatrix** [comment]
Updated Wiki with RC Specs
